import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import TanStackWrapper from "./utils/Wrapper/TanStackWrapper";


const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Intern App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={poppins.className}>
        <TanStackWrapper>{children}</TanStackWrapper>
      </body>
    </html>
  );
}
